package engine;

import model.ILatentEntity;
import model.WordEntity;

import com.google.gson.Gson; // Google's library for parsing JSON into Java objects.
import java.io.FileReader; // Import the class responsible for reading text files character by character.
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Handles data ingestion and parsing.
 * Reads raw JSON files generated by Python and converts them into structured Java objects (Entities)
 */
public class GsonDataLoader implements IDataLoader{

    /**
     * A private Data Transfer Object used exclusively by Gson
     */
    private static class JsonWord {
        String word;
        double[] vector;
    }

    /**
     * Reads the full-dimensional and PCA-reduced JSON files, merges them by word,
     * and returns a consolidated list of objects (WordEntity).
     */
    @Override
    public List<ILatentEntity> loadEntities(String pathFull, String pathPCA) throws IOException {

        // Initialize the JSON parser
        Gson gson = new Gson();

        // --- Step 1: Read Full Vectors Data ---
        FileReader fullReader = new FileReader(pathFull); // Open a stream to read the raw text from the JSON file on the disk.
        JsonWord[] fullWordsArray = gson.fromJson(fullReader, JsonWord[].class); // Parse the JSON text directly into a Java array of JsonWord objects.
        fullReader.close();

        // --- Step 2: Read PCA Vectors Data ---
        FileReader pcaReader = new FileReader(pathPCA); // Open a stream to read the raw text from the JSON file on the disk.
        JsonWord[] pcaWordsArray = gson.fromJson(pcaReader, JsonWord[].class); // Parse the JSON text directly into a Java array of JsonWord objects.
        pcaReader.close();

        // --- Step 3: Build a fast lookup dictionary for PCA vectors ---
        // Creates a HashMap for retrieval time during the merging phase.
        Map<String, double[]> dictionaryPCA = new HashMap<>();
        for (int i = 0; i < pcaWordsArray.length; i++) {
            JsonWord currentPcaItem = pcaWordsArray[i];
            dictionaryPCA.put(currentPcaItem.word, currentPcaItem.vector); // Insert the data into the dictionary: The text is the key, the array is the value.
        }

        // --- Step 4: Putting it all together
        List<ILatentEntity> finalEntitiesList = new ArrayList<>(); // The main dictionary

        for (int i = 0; i < fullWordsArray.length; i++) {
            JsonWord currentFullItem = fullWordsArray[i];
            String wordText = currentFullItem.word;
            double[] mathVector = currentFullItem.vector;

            // Looking up where this word lives on our 2D/3D map
            double[] displayVector = dictionaryPCA.get(wordText);

            // Ensure data integrity before creating the Entity
            if (displayVector != null) {
                WordEntity newEntity = new WordEntity(wordText, mathVector, displayVector);
                finalEntitiesList.add(newEntity);
            }
        }

        return finalEntitiesList;
    }
}